### ISSUE TITLE
issue running preprocess_formulas

### ISSUE THREAD

**Issue by anupamme** [harvardnlp/im2markup#1]
when I run 

python scripts/preprocessing/preprocess_formulas.py --mode normalize --input-file data/sample/formulas.lst --output-file data/sample/formulas.norm.lst

I get

2016-10-05 05:29:51,614 root  INFO     Script being executed: scripts/preprocessing/preprocess_formulas.py
D(T)=\left(\begin{array}{cc}a(T)&0\\0&a(T)^{-1}\end{array}\right) \\ |a(T)|>1 

{ [ParseError: KaTeX parse error: Expected 'EOF', got '\\' at position 68: rray}\right) \\̲ |a(T)|>1 ] name: 'ParseError', position: 68 }
A_{ab} \stackrel\mathrm{ def}{\equiv} \frac{\partial ^2L_\mathrm{ q}}{\partial\dot{q}_a^{n_a}\partial \dot{q}_b^{n_b}}. 
A _ { a b } \stackrel 
[TypeError: Cannot read property 'type' of undefined]
2016-10-05 05:29:52,441 root  INFO     Jobs finished

I am running it on an ubuntu machine.

Let me know how to fix this.

**Comment by da03** [comment]
Did the script produce the output file `data/sample/formulas.norm.lst`? If so, you can just ignore that. The reason is that KaTex cannot parse some formulas (while pdflatex can render them), and we simply write a newline to the outputfile when we encounter those cases.

**Comment by wozhenmingdoubeizhanle** [comment]
> Did the script produce the output file `data/sample/formulas.norm.lst`? If so, you can just ignore that. The reason is that KaTex cannot parse some formulas (while pdflatex can render them), and we simply write a newline to the outputfile when we encounter those cases.

hello ，I have the same problem, The script output an error and produce a empty output file  data/sample/formulas.norm.lst, so how can i fix this problem? this is the error i get:
![image](https://user-images.githubusercontent.com/37336300/61717547-e0832680-ad93-11e9-83ae-bc0cf374dc72.png)

**Comment by SuperHHzy** [comment]
Hi, did you solve your problem? I also encountered the situation of generating an empty formulas.norm.lst, can you tell me how you solved this problem?
