### ISSUE TITLE
error when test the big dataset

### ISSUE THREAD

**Issue by qiangruoyu** [harvardnlp/im2markup#20]
when i use the model test the dataset that is big,I meet an error.How to deal with it?
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/cutorch/Tensor.lua:14: cuda runtime error (59) : device-side assert triggered at /root/torch/extra/cutorch/lib/THC/generic/THCTensorCopy.c:18
stack traceback:
	[C]: in function 'copy'
	/root/torch/install/share/lua/5.1/cutorch/Tensor.lua:14: in function 'localize'
	src/model/model.lua:598: in function 'feval'
	src/model/model.lua:885: in function 'step'
	src/train.lua:116: in function 'train'
	src/train.lua:300: in function 'main'
	src/train.lua:306: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50

**Comment by qiangruoyu** [comment]
The reason for the problem is a picture, but I didn't find anything special about it.

**Comment by qiangruoyu** [comment]
![1](https://user-images.githubusercontent.com/31842600/53339160-7ed3a300-3940-11e9-83e7-a4d6db68d99f.png)

**Comment by da03** [comment]
Weird. Is that picture from our provided dataset im2latex-100k?

**Comment by qiangruoyu** [comment]
> Weird. Is that picture from our provided dataset im2latex-100k?

no，the picture is from my dataset .

**Comment by da03** [comment]
Hmm I think there might be some format issue here. Probably you need to convert it to a grayscale image first.

**Comment by qiangruoyu** [comment]
> Hmm I think there might be some format issue here. Probably you need to convert it to a grayscale image first.

I've done this step.

**Comment by qiangruoyu** [comment]
> Hmm I think there might be some format issue here. Probably you need to convert it to a grayscale image first.

Could it be that the index is out of bounds?The size of the picture is (143,61)

**Comment by da03** [comment]
Interesting. That size is small, yet I think it should suffice to get a non-zero feature map size after those pooling layers...

**Comment by qiangruoyu** [comment]
> Interesting. That size is small, yet I think it should suffice to get a non-zero feature map size after those pooling layers...

Author , do you have the code that use pytorch?

**Comment by Miffyli** [comment]
@qiangruoyu 

See this project (linked by @da03 in an another issue): https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/im2text.md
