### ISSUE TITLE
not working for below type of images (other than given by you). I think we need to put images in particular format

### ISSUE THREAD

**Issue by vyaslkv** [harvardnlp/im2markup#31]
I tested on below type of images and it is giving results like (one diterminant & one matrix)
\hspace { 0 . 5 c m }
\hspace { 5 m m }
![determ](https://user-images.githubusercontent.com/33617789/71763930-195d2500-2f08-11ea-9520-e8a4351f7b18.png)
![matrix](https://user-images.githubusercontent.com/33617789/71763936-25e17d80-2f08-11ea-831c-cb96647de848.png)

**Comment by vyaslkv** [comment]
![int](https://user-images.githubusercontent.com/33617789/71764189-8ec9f500-2f0a-11ea-9b4c-2df8a94169e0.png)
for this also not working

giving results as 
\begin{array} { r c l } \end{array}

**Comment by vyaslkv** [comment]
I have even done the preprocessing step but still not getting results:
onmt_preprocess -data_type img \
                -src_dir data/im2text/images/ \
                -train_src data/im2text/src-train.txt \
                -train_tgt data/im2text/tgt-train.txt -valid_src data/im2text/src-val.txt \
                -valid_tgt data/im2text/tgt-val.txt -save_data data/im2text/demo \
                -tgt_seq_length 150 \
                -tgt_words_min_frequency 2 \
                -shard_size 500 \
                -image_channel_size 1

**Comment by vyaslkv** [comment]
is there any way I could convert my images to your type of images

**Comment by vyaslkv** [comment]
If I need to retrain the model for my type of images then can you tell me the format it will be required 

format of data to retrain the model using python

**Comment by vyaslkv** [comment]
is there any dataset which I could use with the python implementation to train the model and get the results on normal other images as well

**Comment by vyaslkv** [comment]
http://bit.ly/2E7H8tX

I found the above data but it is in different format can you help me how can I use this type of data for training

**Comment by da03** [comment]
Sorry for the delay. Are you training a new model or are you using the pretrained one? The pretrained one is only trained on a particular rendering setup so it's not surprising that it fails on out-of-training-distribution data at test time. To make it work, a new model needs to be trained with data encompassing enough test-style images (font, size, etc).

**Comment by vyaslkv** [comment]
I used the pretrained model. Thanks for replying!!
