### ISSUE TITLE
[Please Respond] Can you help me training the model for to recognize the out of given data image set

### ISSUE THREAD

**Issue by vyaslkv** [harvardnlp/im2markup#33]
Can you please help in the steps like generating the data by data augmenting and preparing the data for training

**Comment by da03** [comment]
Please refer to #32. I think the feasible way would be collecting a large handwritten dataset (and it'd be nice if it can be made public). 

Data augmentation would help a bit, but it is hard to design augmentation techniques to encompass all variation patterns in the real world. We released a dataset of synthetic handwritten formulas by replacing symbols with handwritten symbols (kindly provided by the authors of detexify) which can be found here: http://lstm.seas.harvard.edu/latex/data/. While combining this dataset with the digital im2latex-100k dataset (and adding noise and randomly reshaping/rotating) might get a more robust model, there are still variations not being captured in these synthetic datasets: for example, varying baselines.
