### ISSUE TITLE
There is a bug in preprocess_latex.js

### ISSUE THREAD

**Issue by hengyeliu** [harvardnlp/im2markup#36]
When I used your script to normalize the formula, I found that there was an illegal LaTeX symbol 'ule' generated. After checking, I found that the symbol was originally '\rule', but the program mistook the '\r' in front of the symbol for a carriage return.  This problem was solved when I changed the "\ rule {" to "\ \rule {" in line 344 of the preprocess_latex.js.

**Comment by da03** [comment]
Nice catch, would you mind submitting a pull request to fix this bug?

**Comment by hengyeliu** [comment]
> Nice catch, would you mind submitting a pull request to fix this bug?

Of course not,the pull request has been submitted.

**Comment by da03** [comment]
Thanks!
