### ISSUE TITLE
Offset in dataset

### ISSUE THREAD

**Issue by MatthiasRMS** [harvardnlp/im2markup#4]
It looks like there is an offset in the dataset provided: 

In im2latex_train.lst, the first line is:

`1   60ee748793   basic`

Which corresponds to this equation:
`\int_{-\epsilon}^\infty dl\: {\rm e}^{-l\zeta}	\int_{-\epsilon}^\infty dl' {\rm e}^{-l'\zeta}	ll'{l'-l \over l+l'} \{3\,\delta''(l) - {3 \over 4}t\,\delta(l) \} =0.		\label{eq21}`

But the image 60ee748793 doesn't match. This image matches with the equation of the next line: 

`2   66667cee5b   basic`

Which is: 

`ds^{2} = (1 - {qcos\theta\over r})^{2\over 1 + \alpha^{2}}\lbrace dr^2+r^2d\theta^2+r^2sin^2\theta d\varphi^2\rbrace -{dt^2\over  (1 - {qcos\theta\over r})^{2\over 1 + \alpha^{2}}}\, .\label{eq:sps1}`

I see in the sample date in the repo starts at line index 0 which would explain that you chose to consider the first line as line 0, and would explain the "offset". 
However, it would mean that the first equation doesn't have a matching image. 

Did I miss something or is there really an issue with the dataset ?

Thanks for your help !

**Comment by Miffyli** [comment]
Hey.

Line indexing starts from 0, i.e. line number 1 means the second line and thus the first item in train list corresponds to the formula starting `ds^2{2}` .
The whole dataset is split into three lists for standardized testing, and "im2latex_train.lst" is only one of these.  If you check "im2latex_validate.lst" you can see the first item being `0 5abbb9b19f basic`, which is the missing formula you were wondering.

Hope this cleared things up.
